# -*- coding: utf-8 -*-
"""CreatingDataFrames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gppnofg8nFm6ZfPLZhVRwPZRtDXpRc2v
"""

Employee={
    'Name':['Ahmad','Sana','Bilal','Mehak'],
    'Department':['HR','IT','Finance','IT'],
    'Salary':[50000,60000,55000,65000]}

Employee

import pandas as pd

df=pd.DataFrame(Employee)

df

df['Salary']=(df['Updated_Salary']*1.10).astype(int)

df
#df['Updated_Salary'] = (df.pop('Salary') * 1.10).round(0).astype(int) this method is used to update the column by the number u want and also replace
#the column with new name

Updated_Salary,Salary=df[['Updated_Salary','Salary']].to_numpy().T

Updated_Salary,Salary

df.to_csv('Employee.csv',index=False)

df

df=pd.read_csv('Employee.csv')

df

"""# New Section"""

Sales_Data={
    "Month":["Jan","Feb","March"],
    "Product_A":[1200,1100,1300],
    "Product_B":[1500,1450,1650],
    "Product_C":[1800,1700,1750]
}

df=pd.DataFrame(Sales_Data)

df

df[['Product_A', 'Product_B', 'Product_C']].sum()

df[['Product_A','Product_C']].to_csv('Sales_Subset.csv',index=False)

df

pd.read_csv('Sales_Data.csv')