# -*- coding: utf-8 -*-
"""Filehandling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBTajdwgP9RAnMixQxegqr3yaILHZXGM

File handling refers to the process of performing operations on file such as creating,reading,writing and closing it through the interfacce.

To open a file, we can use **open()** function, which requires file-path and mode as arguments:
**file = open('filename.txt', 'mode')**

filename.txt: name (or path) of the file to be opened.
mode: mode in which you want to open the file (read, write, append, etc.).
"""

f=open("/content/sample_data/README.md")

my_file=open("/content/sample_data/README.md","r")
print(my_file)

"""This code opens file "/content/sample_data/README.md" in read mode. If the file exists, it returns a file object connected to that file; if the file does not exist, Python raises a FileNotFoundError.

A file object in Python is like a handler / connection between your program and the file stored on disk.

Think of it as a remote control that lets you:

Read from the file (f.read())

Write to the file (f.write())

Move around inside the file (f.seek())

Close the file when done (f.close())
"""

f.close()
#Closing a File
#The file.close() method closes the file and releases the system resources.
# If the file was opened in write or append mode, closing ensures that all changes are properly saved.

"""Checking file properties"""

my_file=open("/content/sample_data/README.md")
print("Filename:",my_file.name)

print("mode",my_file.mode)

print("is closed:",my_file.closed)

my_file=open("/content/sample_data/README.md")

content=my_file.read()

print(content)

my_file=open("/content/sample_data/README.md","w")

my_file.write("hello hi baby ar u doing well")

with open("/content/sample_data/README.md","r") as f:
 print(f.read())

my_file=open("My_file","w")

import os
os.getcwd()

file=open("My_file","w")

file.write("hello how are u doing")
file.close()

with open("My_file","r+") as f:
  # f.append("\n i am doing good")
  # f.read()
  f.write("hello")
  print(f.read())

with open("My_file","r+") as  f:
 f.write("\n hello, thankyou i am doing good ")
 print(f.read(5))
 #print(cont)

if os.path.exists("My_file"):
  os.remove("My_file")
else:
  print("it does not exixt")

os.getcwd()

