# -*- coding: utf-8 -*-
"""practiceprogramms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgpD9NUaS-3eacB9-2Eo32sw-vBhZhhT

Find the area of circle of radius 5
"""

import math

radius=5
area = math.pi * (radius**2)
print(f'the area of the circle with radius {radius} is:{area}')

"""Swap variables of two variables with out using temporay variable"""

from re import A
a=5
b=8
a,b=b,a
print(f'a={a},b={b}')

"""write a program to remove duplicates in list"""

lst=[1,2,3,4,5,6,1,2,3,4]
uniqe_list=list(set(lst))
print(uniqe_list)

"""write a program to find a largest and smallest elements in list"""

lst=[1,23,4,5,78,59]
largest=max(lst)
smallest=min(lst)
print(f'the largest number in the list is: {largest}')
print(f'the smallest number in the list is :{smallest}')

"""write a program to check if the number is palindrome or not"""

num=12344321
num_str=str((num))
if num_str == num_str[::-1]:
  print('the num is palindrome')
else:
    print('it is not')

"""write a program to culculate the sum of all even numbers in a list"""

lst=[1,2,3,4,5,6,7,8,9,10]
even_sum=sum([num for num in  lst if num%2==0])
print(f'the sum of all even numbers in a string is :{even_sum}')

"""write a program to find the factorial of a number"""

num=5
factorial=1
for i in range(1,num+1):
  factorial *=i
print(f'the factorial of {num} is:{factorial}')

import math

num=5
math.factorial(5)

"""write a programm to find the greatest common divisor of two numbers using euclidean algorithm"""

def gcd(a,b):
  if b==0:
    return a
  else:
      return gcd(b ,a % b)
num1,num2=48,66
gcd=gcd(num1,num2)
print(f'the GCD of {num1} and {num2} is:{gcd}')

"""write a program to sort a dictionaries based on specific key"""

lst=[{'name':'jnon','age':25},
     {'name':'ton','age':96},
     {'name':'son','age':86},
     {'name':'tonn','age':16}]
key='age'
sorted_list=sorted(lst,key=lambda x: x[key])
print(sorted_list)