# -*- coding: utf-8 -*-
"""Tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O56tZROu4VQAUp-cBZVsRfvM3RuGHR5h

**Tuple** a tuple is  sequence of immutable objects separated by the commas and whole sequence enclosed in parenthesis in many ways tuples behave like lists except that tuple are immutable therefore tuples do not have **insert(),pop(),remove(),copy(),delete(),reverse(),sort(),append() and extend()old. We will check them all and perform operations on a tuple
**
"""

tuple1=(1,2,3,2,4,5,1,True,False,'Hello')
tuple1

"""Count() : in tuple count counts the nuumber of times a particular item or object appears in tuple"""

occurance_of_2=tuple1.count(2)
print(f"the number appears: {occurance_of_2} times")

"""Index: the index of the element is found using .index() method"""

tt=tuple1.index('Hello')
tt

"""Slicing
tuple1[2:5:2] means start from index 2 and stop at 5 but does not include 5 and give step of 2
"""

tuple1[2:5:2]

"""

>  Accessing Tuple elements

"""

tuple1[7]

tuple1[-1]

"""Reverse"""

tuple1[::-1]

"""Range of index"""

print(tuple1)
tuple1[1:6:2]

tuple1[:5]

"""tuples are immutable so can not be changed

> but can be cahnged to list forst then changed



"""

x=('apple',1,2,3,'cherry')
tup=list(x)
tup

tup[1]='kiwi'
tup

tupl=tuple(tup)
tupl

"""unpacking of tuple"""

tup=('apple','cherry','kiwi')
tup

(green,yellow,red)=tup
print(green)

tup2=(1,2,3)
tup2

(hello,yello,jellow)=tup2
print(hello)

fruits=('apple','cherry','kiwi','banana')

(yellow,green,*red)=fruits
print(red)

"""Loop in tuple"""

tup=[1,2,3,4,5,6,7,8]
for x in tup:
  print(x)

tupl=('apl','banana','kwi','cherry')
for i in range(len(tupl)):
  print(tupl[i])

for i in range(len(tupl)):
 print(i)

"""Using while loop"""

i=0
while i < len(tupl):
  print(tupl[i])
  i +=1

"""joining tuples

"""

tupl1=(1,2,3,'hello')
tuple2=(1,23,4,7)
result=tupl1+tuple2
print(result)